import "./globals.css";
import SessionProviders from "./sessionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProviders>{children}</SessionProviders>
      </body>
    </html>
  );
}
